# Generated by Django 4.0 on 2021-12-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=models.FileField(upload_to='images/'),
        ),
    ]
